name: nwl-personal-goals-server

services:
  pg:
    image: bitnami/postgresql:17.4.0
    ports: 
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=inorbit